config/routes.rb
TarasBychko::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'

  resources :gallery

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/image.rb
class Image < ActiveRecord::Base

  belongs_to :room

end

app/models/room.rb
class Room < ActiveRecord::Base

  has_many :images

  def cover
    images.where({:type => 'cover'}).first
  end

  def self.enabled
    where(:enabled => true)
  end

  def self.valid?(room_name)
    enabled.pluck(:name).include? room_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery :with => :exception
  before_filter :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    { :locale => I18n.locale }
  end

end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController

  def index

  end

  def show
    room_name = params[:id]
    redirect_to root_path unless Room.valid?(room_name)
    @room = Room.find_by_name(room_name)
  end

  def create

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @rooms = Room.enabled
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 9]><html class="no-js lt-ie9"><![endif]-->
<!--[if (gt IE 10)|!(IE)]><!--> <html> <!--<![endif]-->
    <head>
      <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
      <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
      <title>Taras Bychko</title>
      <%= stylesheet_link_tag    "application", :media => "all", "data-turbolinks-track" => true %>
      <%= stylesheet_link_tag "vendor/flat-ui", :media => "all" %>
      <%= csrf_meta_tags %>
    </head>
    <body>

      <div id="fullPage" class="container">
        <%= render :partial => 'shared/header' %>
      </div>
      <%= yield %>
      <div id="fullPage" class="container">
        <%= render :partial => 'shared/footer' %>
      </div>

        <%= javascript_include_tag "application" %>
    </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
    <!--Facebook likes -->
    <div class="fb-like" data-send="true" data-width="300" data-show-faces="true"></div>

    <!-- Google + -->
    <div class="g-plusone white" data-annotation="inline" data-width="300"></div>
    <script type="text/javascript">
        (function() {
            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
            po.src = 'https://apis.google.com/js/platform.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();
    </script>

    <!-- Twitter -->
    <a href="https://twitter.com/share" class="twitter-share-button" data-lang="en">Tweet</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=594819643946068";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <div class="center">
      &copy <%= link_to t('.taras'), 'https://www.facebook.com/taras.bychko', :target => '_blank', :style=>"color: #34495E"%>
     </div>
     <small class="pull-right">
      2013 - <%= Time.now.year %>
    </small>
    <br/>

    <small class="tiny center" >
      &copy <%= link_to t('.designed_by'), 'https://www.facebook.com/tanosatap', :target => '_blank', :style=>"color: #34495E"%>
    </small>
</div>

app/views/shared/_header.html.erb
<div class="home-header">
    <h4 class="inline">
      <%= t('.title') %>
    </h4>
    <ul class="list-inline pull-right" style="margin-top: 20px;">
      <li><%= link_to t('.home'), root_path %></li>
      <li><%= link_to t('.gallery'), gallery_index_path %></li>
      <li><%= link_to t('.blog'), '#' %></li>
      <li><%= link_to t('.contacts'), '#' %></li>
      <li><%= link_to t('.about'), '#' %></li>
      <li>
        <%= link_to image_tag('en.gif'), params.merge(:locale => "en") %>
        <%= link_to image_tag('ua.png'), params.merge(:locale => "ua" )%>
      </li>
    </ul>
</div>

app/views/welcome/index.html.erb
<div id="carousel-example-generic" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <% active = 'active' %>
    <% @rooms.each do |room| %>
      <%= content_tag :div, :class =>  "item #{active}" do -%>
        <% active = '' %>
        <%= image_tag "top-beach-hd-wallpaper.jpg" %>
        <div class="carousel-caption">
          <%= link_to t(".#{room.name}"), "/gallery/#{room.name}" %>
        </div>
      <% end %>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="icon-next"></span>
  </a>
</div>

<script type="text/javascript" >
    $(document).ready(function() {
        $('.carousel').carousel()
    });
</script>